### PR TITLE
Web Interface for OTP

### PR DESCRIPTION
**Pull request by Nidhip144**

### CODE REVIEW

**Comment by aswarthm** [comment]
@pulkit-dhamija Check if any changes are required

**Comment by pulkit-dhamija** [comment]
I'm busy right now will do in 30 mins

**Comment by pulkit-dhamija** [comment]
looks good to me @aswarthm .
do a final check and merge

**Comment by aswarthm** [comment]
I am merging the pr

**Comment by bharath-reddy07** [comment]
Nice work

**Pull request merged**
