### PR TITLE
Encoder test

### PR DESCRIPTION
**Pull request by shishiraiyar**
Please accept🥺

### CODE REVIEW

**Comment by bharath-reddy07** [comment]
File is empty what is this

**Comment by bharath-reddy07** [comment]
Can u add click input also for rotary encoder

**Comment by shishiraiyar** [comment]
@bharath-reddy07 added click

**Comment by aswarthm** [comment]
wow very nice

**Comment by aswarthm** [comment]
Thanks for fixing issue #2 
Closing the issue now

**Pull request merged**
